GET http://localhost:3000/subscribers

###

GET http://localhost:3000/subscribers/15

###

POST http://localhost:3000/subscribers
content-type: application/json

{
    "name": "Amazing Person",
    "subscribedToChannel": "Lefteris Giannaros"
}